"""Sketch of the target Python API for the migjorn rewrite.

This is a DESIGN SKETCH, not the final stub — it fixes the *shape* and the *cost
model* the implementation must hit, and it is the source the real ``.pyi`` is
grown from. The surface deliberately stays close to the current library (that
part is good); what changes is underneath and in the guarantees:

  * Handles (`Cell`, `Surface`, ...) are LIVE and CHEAP. There is no `view()` /
    `materialize()` split and no notion of a handle going stale after a
    structural edit to *another* card. `model.cell(7)` always resolves against
    current state. (A handle to a card you `remove()` becomes invalid and raises
    on use — that is the only staleness.)
  * No operation triggers a whole-file reparse. add/remove/renumber/value-edit
    are all local. See docs/04-performance-budget.md for the numbers.
  * Losslessness is unconditional: `parse(t).to_source() == t`, byte for byte.
"""

from collections.abc import Callable, Iterator

__version__: str

# old id -> new id: an explicit dict (unmapped ids unchanged) or a callable.
Mapping = dict[int, int] | Callable[[int], int]


def parse(text: str) -> Model: ...


class Model:
    """A parsed MCNP model: lossless, typed access, cheap iterative editing."""

    def __init__(self, text: str) -> None: ...
    @staticmethod
    def from_file(path: str) -> Model: ...

    def to_source(self) -> str:
        """Re-emit as MCNP text. Byte-identical to the input when unedited; when
        edited, identical except at edited cards. Cost is O(bytes), and O(edited
        cards) beyond the unavoidable output copy — never a reparse."""
    def save(self, path: str) -> None: ...

    @property
    def diagnostics(self) -> list[Diagnostic]: ...

    # --- iteration & lookup (lookups are O(1) via maintained id indices) -----
    def cells(self) -> Iterator[Cell]: ...
    def surfaces(self) -> Iterator[Surface]: ...
    def materials(self) -> Iterator[Material]: ...
    def transforms(self) -> Iterator[Transform]: ...
    def data_cards(self) -> Iterator[DataCard]: ...

    @property
    def num_cells(self) -> int: ...
    @property
    def num_surfaces(self) -> int: ...
    @property
    def num_materials(self) -> int: ...
    @property
    def num_transforms(self) -> int: ...

    def cell(self, id: int) -> Cell | None: ...
    def surface(self, id: int) -> Surface | None: ...
    def material(self, id: int) -> Material | None: ...
    def transform(self, id: int) -> Transform | None: ...

    # --- structural editing (each is local; ~O(num_cards) at worst) ----------
    def add_cell(self, text: str) -> Cell: ...
    def add_surface(self, text: str) -> Surface: ...
    def add_material(self, text: str) -> Material: ...
    def remove_cell(self, id: int) -> bool: ...
    def remove_surface(self, id: int) -> bool: ...
    def remove_material(self, id: int) -> bool: ...
    def remove_transform(self, id: int) -> bool: ...

    # --- whole-model renumbering (defs + every reference, consistently) ------
    def renumber_cells(self, mapping: Mapping) -> None: ...
    def renumber_surfaces(self, mapping: Mapping) -> None: ...
    def renumber_materials(self, mapping: Mapping) -> None: ...
    def renumber_transforms(self, mapping: Mapping) -> None: ...
    def renumber_universes(self, mapping: Mapping) -> None: ...
    def renumber_tallies(self, mapping: Mapping) -> None: ...
    def offset_cells(self, delta: int) -> None: ...
    def offset_surfaces(self, delta: int) -> None: ...

    # --- analysis / composition ---------------------------------------------
    def validate(self) -> list[str]: ...
    def universe_ids(self) -> list[int]: ...
    def extract_universe(self, u: int) -> Model: ...
    def extract_level0(self) -> Model: ...
    def merge(self, others: list[Model]) -> None: ...

    def __str__(self) -> str: ...


class Cell:
    """A live handle onto a cell card."""

    @property
    def id(self) -> int: ...
    @property
    def material(self) -> int | None: ...
    @material.setter
    def material(self, value: int) -> None: ...
    @property
    def density(self) -> float | None: ...
    @density.setter
    def density(self, value: float) -> None: ...
    @property
    def is_void(self) -> bool: ...
    @property
    def like(self) -> int | None: ...

    @property
    def surface_ids(self) -> list[int]: ...
    @property
    def signed_surfaces(self) -> list[int]: ...
    @property
    def cell_refs(self) -> list[int]: ...
    @property
    def universe(self) -> int | None: ...
    @property
    def fill(self) -> Fill | None: ...
    @property
    def params(self) -> list[CellParam]: ...
    @property
    def well_formed(self) -> bool: ...
    @property
    def text(self) -> str: ...

    def param(self, key: str) -> CellParam | None: ...
    def set_param(self, key: str, value: str) -> bool: ...
    def add_param(self, text: str) -> None: ...
    def remove_param(self, key: str) -> bool: ...
    def add_surface(self, surface: int) -> None: ...
    def remove_surface(self, id: int) -> bool: ...
    def add_complement(self, id: int) -> None: ...
    def remove_complement(self, id: int) -> bool: ...
    def append_comment(self, text: str) -> None: ...


class Surface:
    """A live handle onto a surface card."""

    @property
    def id(self) -> int: ...
    @property
    def kind(self) -> str: ...
    @property
    def coeffs(self) -> list[float]: ...
    @coeffs.setter
    def coeffs(self, value: list[float]) -> None: ...
    @property
    def transform(self) -> int | None: ...
    @transform.setter
    def transform(self, value: int | None) -> None: ...
    @property
    def reflective(self) -> bool: ...
    @property
    def white(self) -> bool: ...
    @property
    def well_formed(self) -> bool: ...
    @property
    def text(self) -> str: ...

    def set_coeff(self, index: int, value: float) -> None: ...


class Material:
    @property
    def id(self) -> int: ...
    @property
    def entries(self) -> list[tuple[str, float]]: ...
    @property
    def well_formed(self) -> bool: ...
    @property
    def text(self) -> str: ...

    def set_fraction(self, entry: int, value: float) -> None: ...
    def set_zaid(self, entry: int, zaid: str) -> None: ...


class Transform:
    @property
    def id(self) -> int: ...
    @property
    def degrees(self) -> bool: ...
    @property
    def displacement(self) -> tuple[float, float, float]: ...
    @displacement.setter
    def displacement(self, value: tuple[float, float, float]) -> None: ...
    @property
    def rotation(self) -> list[float]: ...
    @property
    def text(self) -> str: ...

    def set_rotation(self, rotation: list[float]) -> None: ...


class Fill:
    @property
    def universe(self) -> int: ...
    @property
    def starred(self) -> bool: ...
    @property
    def transform(self) -> str | None: ...


class CellParam:
    @property
    def key(self) -> str: ...
    @property
    def particle(self) -> str | None: ...
    @property
    def starred(self) -> bool: ...
    @property
    def value(self) -> str: ...


class DataCard:
    @property
    def name(self) -> str: ...
    @property
    def particle(self) -> str | None: ...
    @property
    def starred(self) -> bool: ...
    @property
    def text(self) -> str: ...


class Diagnostic:
    @property
    def severity(self) -> str: ...
    @property
    def message(self) -> str: ...
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...


class MergeError(ValueError):
    """Raised by ``Model.merge`` on a shared cell/surface/material/transform id."""
