[package]
name = "migjorn"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Fast, lossless MCNP input parser and editor"

[dependencies]
migjorn-syntax.workspace = true
compact_str.workspace = true
rayon.workspace = true
rustc-hash.workspace = true

[dev-dependencies]
toml = "0.8"
